import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: "./fonts/Inter/Inter-Regular.woff",
  variable: "--font-inter",
});

const interBold = localFont({
  src: "./fonts/Inter/Inter-Bold.woff",
  variable: "--font-inter-bold",
});

const interSemiBold = localFont({
  src: "./fonts/Inter/Inter-SemiBold.woff",
  variable: "--font-inter-semi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${interBold.variable} ${interSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
